repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: trailing-whitespace
